#!/bin/sh
#
#  Copyright (C) 2006 
#  Licensed under GPL, see LICENSE file or http://www.gnu.org/licenses/gpl.html



thishost=`uname -n`

tar cvf - /etc/mods /etc/init.d/*vmps* /secure/*vmps* /opt/vmps /etc/vmps /var/spool/cron/tabs /mysqldata/inventory | gzip > vmps.$thishost.tgz

ls -al vmps.$thishost.tgz

