#!/bin/sh
#
#/etc/init.d/radius
#
### BEGIN INIT INFO
# Provides: radiusd
# Description: Starts the radiusd daemon
### END INIT INFO

case "$1" in
start)
	[ -f /usr/local/sbin/radiusd ] || exit 1
	#/usr/local/sbin/radiusd -A
	nohup /usr/local/sbin/radiusd -Xx >> /usr/local/var/log/radius/radius.log &
	;;

stop)
	pkill radiusd
	;;

restart)
	$0 stop
	$0 start
	;;

debug) 
	[ -f /usr/local/sbin/radiusd ] || exit 1
        /usr/local/sbin/radiusd -X
        ;;

*)	echo "Usage: $0 {start|stop|restart|debug}"
	exit 1
	;;
esac
exit 0
