#!/bin/sh
#
# Solaris:
#   ln -s /etc/init.d/vmps_lastseen /etc/rc3.d/S99vmps_lastseen
# Suse Linux:
#   ln -s /etc/init.d/vmps_lastseen /sbin/rcvmps_lastseen
#   chkconfig vmps_lastseen on
#
### BEGIN INIT INFO
# Provides:       vmps_lastseen
# Required-Start: $network $remote_fs mysql
# Required-Stop:
# Default-Start:  2 3 5
# Default-Stop:
# Description:    Start the Vmps lastseen daemon
### END INIT INFO



mode=$1    # start or stop
CMD='tail -f /var/log/messages |/opt/nac/bin/vmps_lastseen'

case "$mode" in
  'start')
    # Start daemon
    nohup tail -f /var/log/messages | /opt/nac/bin/vmps_lastseen &
    #echo $CMD
    #$CMD
    ;;

  'stop')
    #pkill ".*vmps_lastseen.**"
    #pkill -f "$CMD"
    pkill -f "tail -f /var/log/messages | /opt/nac/bin/vmps_lastseen"
    ;;

  'restart')
    # Stop the service and regardless of whether it was
    # running or not, start it again.
    $0 stop;
    sleep 1;
    $0 start;
    ;;

  *)
    # usage
    echo "Usage: $0 start|stop|restart"
    exit 1
    ;;
esac
