#!/bin/sh
#
# /etc/init.d/vmps
#
# 

case "$1" in
start)
	[ -f /opt/vmps/vmpsd ] && \
	    [ -f /etc/vlan.db ] || exit 1

        #-l  log level
        #  o   0x0100 -- fatal errors only
        #  o   0x0200 -- informational messages
        #  o   0x0400 -- print warnings
        #  o   0x0800 -- print debug messages; very verbose
        #  o   0x0001 -- system
        #  o   0x0002 -- parser
        #  o   0x0004 -- vqp
        #  Good: 0x0804 and bit less: 0x0F04

	## External testing: port 10000; no on mgt net
        /opt/install/vmpsd/vmpsd -p 10000 -e /opt/vmps/vmpsd_external -l 0x0804 -a 127.0.0.1

	#/opt/install/vmpsd/vmpsd -f /etc/vlan.db -l 0x0804 -a 192.168.245.40
	##/opt/vmps/vmpsd -f /etc/vlan.db -l 0x0F04 -a 192.168.245.40
	#/opt/vmps/vmpsd -e /opt/vmps/vmpsd_external  -l 0x0804 -a 192.168.245.40
	#/opt/vmps/vmpsd -e /opt/install/vmpsd/external/ext.pl  -l 0x0804 -a 192.168.245.40

	#/opt/vmps/vmpsd -f /etc/vlan.db -l 0x0F04 -a 192.168.245.19
	#/usr/local/bin/vmpsd -f /etc/vlan.db -a 192.168.245.19
	#/usr/local/bin/vmpsd -d -f /etc/vlan.db -l 0x0F04 -a 192.168.245.19
	#su vmps -c /usr/local/bin/vmpsd -d -f /etc/vlan.db -l 0x0F04 -a 192.168.245.19

	#/usr/local/bin/vmpsd -d -f /etc/vlan.db -l 0x0F08 -a 192.168.245.19
	#/usr/local/bin/vmpsd -f /etc/vlan.db -l 0x0F07 -a 192.168.245.19
	#/usr/local/bin/vmpsd -f /etc/vlan.db -l 0x0F04 -a 192.168.245.19
	#/usr/local/bin/vmpsd -f /etc/vlan.db -l 0x0804 -a 192.168.245.19
	;;

reload)
        pkill -HUP vmpsd;
        ;;

restart)
        $0 stop;
        $0 start;
	;;

stop)
        pkill vmpsd
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
